# 1. Sequential numbering with action description
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_exe_dll_log_1.txt";$tempFile="P:\temp\vs_strings_exe_dll_sorted_1.txt";if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll','.pdb','.lib'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 2. Including file size and timestamp
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_exe_dll_log_2.txt";$tempFile="P:\temp\vs_strings_exe_dll_sorted_2.txt";if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line) | $(Get-Date) | Size: $($_.Length)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 3. Including a timestamped header
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_log_run_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt";$tempFile="P:\temp\vs_strings_sorted_run_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt";"===== Log for run at $(Get-Date) =====" | Out-File $of -Append;if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 4. Another sequential example with timestamped log
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_log_run_503.txt";$tempFile="P:\temp\vs_strings_sorted_run_503.txt";"===== Log for run at $(Get-Date) =====" | Out-File $of -Append;if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 5. Including date for unique filenames
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$date=$(Get-Date -Format "yyyy-MM-dd_HH-mm-ss");$of="P:\temp\vs_strings_log_$date.txt";$tempFile="P:\temp\vs_strings_sorted_$date.txt";if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 6. Backup with sequential numbering and timestamp
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_log_703.txt";$backup="P:\temp\vs_strings_backup_$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss').txt";$tempFile="P:\temp\vs_strings_sorted_703.txt";if(Test-Path $of){Copy-Item $of -Destination $backup};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 7. Sequential example with size and timestamp
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_exe_dll_log_803.txt";$tempFile="P:\temp\vs_strings_exe_dll_sorted_803.txt";if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line) | $(Get-Date) | Size: $($_.Length)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force

# 8. Sequential log example with extra extensions
$td="C:\Program Files\Microsoft Visual Studio\2022\Enterprise";$of="P:\temp\vs_strings_exe_dll_pdb_lib_log_903.txt";$tempFile="P:\temp\vs_strings_exe_dll_pdb_lib_sorted_903.txt";if(!(Test-Path $of)){New-Item -ItemType File -Path $of};gci $td -r -File|?{$_.Extension -in '.exe','.dll','.pdb','.lib'}|%{$o=strings $_.FullName|Select-String "^(Dbg|Dev|Internal|Undocumented|Assert|Get|Set|Create|Delete|Open)[A-Za-z0-9_]+$";if($o){"$($_.FullName) $($o.Line)"|Out-File $of -Append}};sort $of|Get-Unique|Out-File $tempFile;Copy-Item $tempFile -Destination $of -Force
